### ISSUE TITLE
question

### ISSUE THREAD

**Issue by B-Nerd** [flathub/io.github.snesrev.Zelda3#3]
not really a issue but just a question are you part of the snesrev discord this question also is for @heroesiiifan @marc0x1 @pizzadude  also what is your user name if you people are on discord i think people wanna chat with you

**Comment by marc0x1** [comment]
Hi, I don't use discord (but I have a matrix account) , feel free to leave a question here.

> not really a issue but just a question are you part of the snesrev discord this question also is for @heroesiiifan @marc0x1 @pizzadude also what is your user name if you people are on discord i think people wanna chat with you

**Comment by B-Nerd** [comment]
does that also go for pizza & heroes

**Comment by heroesiiifan** [comment]
I also don't have a discord account. But I checked it out. It was probably about the fact that the shaders are active by default.

I added an additional question. Can now be selected on first start...
